using SCFirstOrderLogic.SentenceFormatting;

namespace SCFirstOrderLogic
{
    /// <summary>
    /// Class for Skolem function symbols, which are generated by the sentence normalisation process and feature in sentences in conjunctive normal form (CNF).
    /// </summary>
    /// <remarks>
    /// <para>
    /// NB #1: Doesn't override equality or hash code, so uses reference equality;
    /// and the normalisation process creates exactly one instance per variable scope - thus achieving standardisation
    /// without having to muck about with anything like trying to ensure names that are unique strings
    /// (which only sentence formatting logic, not the symbol itself, should care about).
    /// </para>
    /// <para>
    /// NB #2: As with standardised variables, OPTIONAL value semantics for equality might be useful.
    /// An equality comparer for this may appear in a future version.
    /// </para>
    /// </remarks>
    public class SkolemFunctionSymbol
    {
        /// <remarks>
        /// Intended only for construction by the normalisation process.
        /// (Internal means we don't have to validate that the variable is standardised).
        /// </remarks>
        internal SkolemFunctionSymbol(StandardisedVariableSymbol variableSymbol, Sentence originalSentence)
        {
            VariableSymbol = variableSymbol;
            OriginalSentence = originalSentence;
        }

        /// <summary>
        /// Gets the original top-level sentence in which the variable was declared.
        /// Contains all ancestors of the original variable declaration
        /// in the sentence tree - starting with the quantification that declares the variable, and ending with the
        /// root element of the sentence. Intended for use within explanations of query results.
        /// </summary>
        public Sentence OriginalSentence { get; }

        /// <summary>
        /// Gets the underlying (existentially quantified) variable symbol that this Skolem function represents the existential instantiation of.
        /// </summary>
        public StandardisedVariableSymbol VariableSymbol { get; }

        /////// <summary>
        /////// Gets the quantification in which the original variable was declared.
        /////// </summary>
        ////public ExistentialQuantification OriginalVariableScope => .. // Find the variable's declaration in OriginalSentence. It's standardised, so we know it's unique.

        //// TODO-ZZ-FEATURE: We could (should?) include some information about what the function parameters (if any) represent.
        //// (i.e. what universally declared vars are in scope).

        /// <inheritdoc/>
        public override string ToString() => new SentenceFormatter().Format(this);
    }
}
